title: Drone Aviator
baseurl: /
permalink: /:title/
destination: droneaviator
markdown: kramdown
relative_permalinks: false
excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed
